spring:
  datasource:
    url: jdbc:mysql://192.168.16.2:3306/rest_with_spring_boot_udemy?useTimezone=true&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl_auto: none
      show-sql: false